# Generated by Django 5.2.11 on 2026-03-23 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.CharField(blank=True, help_text='Student grade level, e.g. 10', max_length=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='school.school'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('pro', 'Pro'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('school_admin', 'School Admin')], default='learner', max_length=20),
        ),
    ]
