# Generated by Django 5.2.11 on 2026-03-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_grade_customuser_phone_customuser_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_end',
            field=models.DateField(blank=True, help_text='Subscription expiry date for individual pro users', null=True),
        ),
    ]
