# Generated by Django 5.2.11 on 2026-02-25 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('tag', models.CharField(choices=[('beginner', 'Beginner'), ('interactive', 'Interactive'), ('simulator', 'Simulator'), ('critical', 'Critical'), ('deep-dive', 'Deep Dive'), ('advanced', 'Advanced'), ('sandbox', 'Sandbox'), ('comparison', 'Comparison'), ('architecture', 'Architecture'), ('knowledge', 'Knowledge')], default='beginner', max_length=30)),
                ('icon', models.CharField(default='🧠', max_length=100)),
                ('color', models.CharField(default='#00ff88', max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('estimated_time', models.PositiveIntegerField(default=30, help_text='Minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('truefalse', 'True/False'), ('code', 'Code Snippet')], default='mcq', max_length=20)),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(blank=True, max_length=300)),
                ('option_d', models.CharField(blank=True, max_length=300)),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(default='beginner', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('content_md', models.TextField(help_text='Markdown content for this section')),
                ('has_visualizer', models.BooleanField(default=False)),
                ('visualizer_type', models.CharField(blank=True, max_length=50)),
                ('key_insight', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Seconds')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('modules', models.ManyToManyField(blank=True, related_name='concepts', to='modules.module')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_answers', models.PositiveIntegerField()),
                ('time_taken', models.PositiveIntegerField(help_text='Seconds')),
                ('answers_data', models.JSONField(default=dict)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
            ],
        ),
    ]
