# Generated by Django 5.2.11 on 2026-04-12 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('activity', 'Activity'), ('experiment', 'Experiment'), ('example', 'Real-World Example')], default='theory', max_length=20)),
                ('content_md', models.TextField(help_text='Rich markdown content')),
                ('difficulty_level', models.CharField(default='beginner', max_length=20)),
                ('estimated_reading_time', models.PositiveIntegerField(default=5, help_text='Minutes')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('tag', models.CharField(choices=[('beginner', 'Beginner'), ('interactive', 'Interactive'), ('simulator', 'Simulator'), ('critical', 'Critical'), ('deep-dive', 'Deep Dive'), ('advanced', 'Advanced'), ('sandbox', 'Sandbox'), ('comparison', 'Comparison'), ('architecture', 'Architecture'), ('knowledge', 'Knowledge'), ('foundation', 'Foundation'), ('practical', 'Practical')], default='beginner', max_length=30)),
                ('icon', models.CharField(default='🧠', max_length=100)),
                ('color', models.CharField(default='#00ff88', max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('estimated_time', models.PositiveIntegerField(default=30, help_text='Minutes')),
                ('grade_level', models.CharField(choices=[('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12'), ('all', 'All Grades')], default='all', max_length=5)),
                ('prerequisites', models.TextField(blank=True, help_text='Prerequisite modules or knowledge')),
                ('learning_objectives', models.TextField(blank=True, help_text='What students will learn (one per line)')),
                ('video_url', models.URLField(blank=True, help_text='YouTube embed URL or direct video URL for the module intro video', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('truefalse', 'True/False'), ('code', 'Code Snippet')], default='mcq', max_length=20)),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(blank=True, max_length=300)),
                ('option_d', models.CharField(blank=True, max_length=300)),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(default='beginner', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('content_md', models.TextField(help_text='Markdown content for this section')),
                ('has_visualizer', models.BooleanField(default=False)),
                ('visualizer_type', models.CharField(blank=True, max_length=50)),
                ('key_insight', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Seconds')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('resource_type', models.CharField(choices=[('video', 'Video Tutorial'), ('article', 'Article/Blog'), ('book', 'Book/eBook'), ('course', 'Online Course'), ('paper', 'Research Paper'), ('documentation', 'Official Documentation'), ('interactive', 'Interactive Tutorial')], default='video', max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('description', models.TextField(help_text='Brief description of what this resource covers')),
                ('author', models.CharField(blank=True, help_text='Author/Creator name', max_length=200)),
                ('duration', models.CharField(blank=True, help_text='e.g., "45 min", "10 hours", "300 pages"', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('is_free', models.BooleanField(default=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='modules.module')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=5, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_duration', models.PositiveIntegerField(default=40, help_text='Total hours')),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('modules', models.ManyToManyField(blank=True, related_name='learning_paths', to='modules.module')),
            ],
            options={
                'ordering': ['grade'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField(help_text='Full technical definition')),
                ('simple_definition', models.TextField(help_text='Simple definition for class 8-10 students')),
                ('example', models.TextField(blank=True, help_text='Real-world example')),
                ('grade_level', models.CharField(default='all', max_length=5)),
                ('category', models.CharField(blank=True, help_text='e.g. Basics, ML, DL, GenAI', max_length=50)),
                ('related_modules', models.ManyToManyField(blank=True, related_name='glossary_terms', to='modules.module')),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('modules', models.ManyToManyField(blank=True, related_name='concepts', to='modules.module')),
            ],
        ),
        migrations.CreateModel(
            name='PracticalExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('exercise_type', models.CharField(choices=[('code', 'Code Exercise'), ('experiment', 'Experiment'), ('quiz', 'Mini Quiz'), ('project', 'Project'), ('activity', 'Hands-on Activity')], default='activity', max_length=20)),
                ('instructions_md', models.TextField(help_text='Step-by-step instructions in markdown')),
                ('starter_code', models.TextField(blank=True, help_text='Optional starter code template')),
                ('solution_code', models.TextField(blank=True, help_text='Hidden solution code')),
                ('hints', models.JSONField(blank=True, default=list, help_text='Progressive hints as a list')),
                ('grade_level', models.CharField(default='all', max_length=5)),
                ('difficulty', models.CharField(default='beginner', max_length=20)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='modules.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_answers', models.PositiveIntegerField()),
                ('time_taken', models.PositiveIntegerField(help_text='Seconds')),
                ('answers_data', models.JSONField(default=dict)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
            ],
        ),
    ]
