# Generated by Django 5.2.11 on 2026-03-12 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='grade_level',
            field=models.CharField(choices=[('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12'), ('all', 'All Grades')], default='all', max_length=5),
        ),
        migrations.AddField(
            model_name='module',
            name='learning_objectives',
            field=models.TextField(blank=True, help_text='What students will learn (one per line)'),
        ),
        migrations.AddField(
            model_name='module',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Prerequisite modules or knowledge'),
        ),
        migrations.AlterField(
            model_name='module',
            name='tag',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('interactive', 'Interactive'), ('simulator', 'Simulator'), ('critical', 'Critical'), ('deep-dive', 'Deep Dive'), ('advanced', 'Advanced'), ('sandbox', 'Sandbox'), ('comparison', 'Comparison'), ('architecture', 'Architecture'), ('knowledge', 'Knowledge'), ('foundation', 'Foundation'), ('practical', 'Practical')], default='beginner', max_length=30),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('activity', 'Activity'), ('experiment', 'Experiment'), ('example', 'Real-World Example')], default='theory', max_length=20)),
                ('content_md', models.TextField(help_text='Rich markdown content')),
                ('difficulty_level', models.CharField(default='beginner', max_length=20)),
                ('estimated_reading_time', models.PositiveIntegerField(default=5, help_text='Minutes')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='modules.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField(help_text='Full technical definition')),
                ('simple_definition', models.TextField(help_text='Simple definition for class 8-10 students')),
                ('example', models.TextField(blank=True, help_text='Real-world example')),
                ('grade_level', models.CharField(default='all', max_length=5)),
                ('category', models.CharField(blank=True, help_text='e.g. Basics, ML, DL, GenAI', max_length=50)),
                ('related_modules', models.ManyToManyField(blank=True, related_name='glossary_terms', to='modules.module')),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=5, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_duration', models.PositiveIntegerField(default=40, help_text='Total hours')),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('modules', models.ManyToManyField(blank=True, related_name='learning_paths', to='modules.module')),
            ],
            options={
                'ordering': ['grade'],
            },
        ),
        migrations.CreateModel(
            name='PracticalExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('exercise_type', models.CharField(choices=[('code', 'Code Exercise'), ('experiment', 'Experiment'), ('quiz', 'Mini Quiz'), ('project', 'Project'), ('activity', 'Hands-on Activity')], default='activity', max_length=20)),
                ('instructions_md', models.TextField(help_text='Step-by-step instructions in markdown')),
                ('starter_code', models.TextField(blank=True, help_text='Optional starter code template')),
                ('solution_code', models.TextField(blank=True, help_text='Hidden solution code')),
                ('hints', models.JSONField(blank=True, default=list, help_text='Progressive hints as a list')),
                ('grade_level', models.CharField(default='all', max_length=5)),
                ('difficulty', models.CharField(default='beginner', max_length=20)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='modules.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
