# Generated by Django 5.2.11 on 2026-03-13 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_module_grade_level_module_learning_objectives_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('resource_type', models.CharField(choices=[('video', 'Video Tutorial'), ('article', 'Article/Blog'), ('book', 'Book/eBook'), ('course', 'Online Course'), ('paper', 'Research Paper'), ('documentation', 'Official Documentation'), ('interactive', 'Interactive Tutorial')], default='video', max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('description', models.TextField(help_text='Brief description of what this resource covers')),
                ('author', models.CharField(blank=True, help_text='Author/Creator name', max_length=200)),
                ('duration', models.CharField(blank=True, help_text='e.g., "45 min", "10 hours", "300 pages"', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('is_free', models.BooleanField(default=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='modules.module')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
