# Generated by Django 5.2.11 on 2026-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_module_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='grade',
            field=models.CharField(choices=[('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='grade_level',
            field=models.CharField(choices=[('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12'), ('all', 'All Grades')], default='all', max_length=5),
        ),
    ]
