# Generated by Django 5.2.11 on 2026-03-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('student_count', models.PositiveIntegerField()),
                ('interested_plan', models.CharField(choices=[('school_annual', 'School Annual — ₹15,000/yr'), ('school_monthly', 'School Monthly — ₹1,500/mo'), ('demo', 'Request Free Demo')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'School Inquiry',
                'verbose_name_plural': 'School Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
