# Generated by Django 5.2.11 on 2026-03-25 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=300)),
                ('amount', models.PositiveIntegerField(help_text='Amount in paise (1 INR = 100 paise)')),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('plan', models.CharField(choices=[('free', 'Free Trial'), ('monthly', 'Monthly'), ('annual', 'Annual'), ('enterprise', 'Enterprise')], max_length=20)),
                ('student_count', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_orders', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='school.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
