# Generated by Django 5.2.11 on 2026-02-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_type', models.CharField(choices=[('neural_network', 'Neural Network Visualizer'), ('gradient_descent', 'Gradient Descent'), ('activation_fn', 'Activation Function'), ('bias_variance', 'Bias-Variance Tradeoff'), ('linear_regression', 'Linear Regression'), ('classification', 'Classification Boundary'), ('decision_tree', 'Decision Tree'), ('cnn_visualizer', 'CNN Visualizer'), ('tokenizer', 'Tokenization Visualizer'), ('embedding', 'Embedding Explorer'), ('transformer', 'Transformer Architecture'), ('llm_params', 'LLM Parameter Playground'), ('rag_pipeline', 'RAG Pipeline Simulator'), ('agent_flow', 'Agent Flow Simulator'), ('fine_tuning', 'Fine-tuning Playground')], max_length=50)),
                ('parameters', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('simulated_latency_ms', models.FloatField(default=0)),
                ('simulated_tokens', models.PositiveIntegerField(default=0)),
                ('simulated_cost_usd', models.FloatField(default=0)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
